name: FreeVps

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1/6 * * *'

jobs:
  backup:
    name: Load Backup...
    runs-on: ubuntu-latest
    steps:
      - name: Load Backup
        run: |
          mkdir backup
  serverapplications:
  #no run server aplications that block the terminal
    name: Run all server aplications...
    runs-on: ubuntu-latest
    steps:
      - name: Run all server aplications
        run: |
          HOST="ftpupload.net"
          USER="ezyro_36182438"
          PASSWORD="b3e5be2d13f8c6"
          DESTINATION=$1
          ALL_FILES="${@:2}"
          ftp -inv $HOST <<EOF
          user $USER $PASSWORD
          cd $DESTINATION
          mput $ALL_FILES
          bye
          EOF
          

  start:
    name: Start Server...
    runs-on: ubuntu-latest
    steps:
      - name: Show Variables
        run: |
          echo "user: $(whoami)"
          echo "IP: $(curl ifconfig.me -s)"
          
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: 2VPkIZaEANZf1LtILeVzVI8onI8_ATJUNtFU6DMXgeiRRx5T
          SSH_PASS: 12345678
